name: release-solution-to-prod
	# prepare for releasing to prod:
	#   convert solution to managed (using a build PowerPlatform environment for the conversion)
	#   upload the solution to the GitHub artifacts and deploy to the PROD environment
	
	on:
	
	# Triggers the workflow on push or pull request events but only for the main branch
	# push:
	#   branches: [ main ]
	# pull_request:
	#   branches: [ main ]
	
	  workflow_dispatch:
	    inputs:
	      # Change this value
	      solution_name:
	        description: 'name of the solution to worked on from Power Platform'
	        required: true
	        default: temp
	       #Do Not change these values
	      solution_shipping_folder:
	        description: 'folder name for staging the exported solution *do not change*'
	        required: true
	        default: out/ship/
	      solution_outbound_folder:
	        description: 'staging the unpacked solution folder before check-in *do not change*'
	        required: true
	        default: out/solutions/
	      solution_source_folder:
	       description: 'folder name to be created and checked in *do not change*'
	       required: true
	       default: solutions/
	      solution_release_folder:
	       description: 'folder where the released binaries are going to be hosted *do not change*'
	       required: true
	       default: out/release
	              #Do Not change these values
	      solution_exported_folder:
	        description: 'folder name for staging the exported solution *do not change*'
	        required: true
	        default: out/exported/
	      solution_folder:
	        description: 'staging the unpacked solution folder before check-in *do not change*'
	        required: true
	        default: out/solutions/
	      solution_target_folder:
	       description: 'folder name to be created and checked in *do not change*'
	       required: true
	       default: solutions/
	  release:
	    types: [created]
	
	
	env:
	#edit your values here
	  BUILD_ENVIRONMENT_URL: https://massived30.crm.dynamics.com

	  USERNAME: harveyspector@massived30.onmicrosoft.com

	  PRODUCTION_ENVIRONMENT_URL: https://devwork173.crm8.dynamics.com

	  CLIENT_ID: 3a06541f-08f6-4e3d-98a9-0f1273c69ded
	  TENANT_ID: 00e2b26f-9c7a-40bd-8796-c5ac71c37ec1
	  NUGET_VERSION: '4.6.1'
	  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
	
	jobs:
	  export-from-dev-deploy-prod:
	    runs-on: windows-latest
	    # or you can say runs-on: ubuntu-latest
	    env:
	      RUNNER_DEBUG: 1
	
	    steps:
	    - uses: actions/checkout@v2
	      with:
	        lfs: true
	
	    - name: Install Nuget
	      uses: nuget/setup-nuget@v1
	      with:
	        nuget-version: ${{ env.NUGET_VERSION}}
	    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
	      run: nuget restore
	
	    - name: Install dependencies
	      run: dotnet restore
	
	    # - name: Install dependencies
	    #   run: dotnet add package Microsoft.CrmSdk.CoreAssemblies --version 9.0.2.42 Release --no-restore
	
	    - name: Add msbuild to PATH
	      uses: microsoft/setup-msbuild@v1.0.0

	      #with:
	      #  vs-version: "[16.4,16.5]"  #Version of Visual Studio to search; defaults to latest if not specified
	
	    - name: Run MSBuild
	      run: msbuild .\CRM.Plugin.RestrictDeactivate.sln
